name: mien
description: A dynamic config Flutter app

publish_to: 'none' 
version: 1.0.0+1

environment:

dependencies:
  flutter:
    sdk: flutter

  # State Management (Bloc/Cubit)
  flutter_bloc: ^9.0.0

  # Local DB: Drift
  drift: ^2.25.0
  sqlite3_flutter_libs: ^0.5.30

  # JSON Serialization
  json_annotation: ^4.9.0

  # MapLibre for mapping
  maplibre_gl: ^0.20.0

  # Additional dependencies
  path: ^1.9.1

  # Optional: Scripting (JS engine)
  # flutter_js: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.4.14
  drift_dev: ^2.25.0
  json_serializable: ^6.9.3
